- name: Install xmonad
  apt: pkg={{ item }}
  with_items:
    - xmonad
    - suckless-tools
    - gnome-panel
  sudo: true
- name: make directory for config
  file: path="~/.xmonad" state=directory
- name: copy xmonad config
  copy: src=xmonad.hs dest=~/.xmonad/xmonad.hs
- name: reset xmonad
  shell: "xmonad --recompile; xmonad --restart"
