---
- name: install python software properties (apt-add-repository)
  apt: pkg=python-software-properties
  sudo: true
- name: "Add Compass PPA"
  apt_repository: repo=ppa:nitrux-team/nitrux-artwork
  sudo: true
- name: Install icon sets
  apt: pkg={{ item }}
  sudo: true
  with_items:
    - compass-icon-theme