---
- name: install python software properties (apt-add-repository)
  apt: pkg=python-software-properties
  sudo: true
- name: "Add the JDownloader PPA"
  apt_repository: repo=ppa:jd-team/jdownloader
  sudo: true
- name: "install: jdownloader"
  apt: pkg=jdownloader-installer
  sudo: true
