---
- name: check if synergy exists
  stat: path=/usr/bin/synergys
  register: synergy_exists
- name: check if we have the right version of synergy
  shell:  synergys --version | grep -Eo "[0-9\.]+" | head -n 1
  register: synergy_v
  when: synergy_exists.stat.exists
- name: download synergy
  get_url: url="http://synergy-project.org/files/packages/synergy-1.7.3-master-ebba77f-Linux-x86_64.deb" dest="/tmp/synergy.deb"
  when: (synergy_v.stdout | default(0) | string) < "1.7.3"
- name: install synergy
  apt: deb="/tmp/synergy.deb"
  when: (synergy_v.stdout | default(0) | string) < "1.7.3f"
  sudo: true
- name: Cleanup download
  file: path="/tmp/synergy.deb" state="absent"
