---
- name: ppa for webupdate8
  apt_repository: repo=ppa:nilarimogard/webupd8
  sudo: true
- name: install gnome-window-applets
  apt: pkg=gnome-window-applets
  ignore_errors: yes
  sudo: true
- name: check for panel applets
  stat: path=/usr/lib/gnome-window-applets
  register: st
- name: If the package wasn't installed, them download window applet deb
  get_url: url=http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/g/gnome-window-applets/gnome-window-applets_0.3-1~webupd8~precise_amd64.deb dest=/tmp/gnome-window-#applets.deb
  when: (not st.stat.exists)
- name: install window applet
  apt: deb=/tmp/gnome-window-applets.deb
  sudo: true
  when: (not st.stat.exists)
- pause: prompt="Check the ppa:nilarimogard/webupd8 for a vivid version" seconds=3
