---
# http://krivatech.blogspot.com.au/2013/01/yaml-syntax-highlighting-in-gedit.html
- name: download lang file
  command:  "wget -O /tmp/yaml.lang http://masood.googlecode.com/svn/trunk/yaml-language-spec/yaml.lang"
- name: copy lang file
  command: "mv /tmp/yaml.lang /usr/share/gtksourceview-3.0/language-specs/"
  sudo: true
- name: give lang file right permissions
  file: path=/usr/share/gtksourceview-3.0/language-specs/yaml.lang mode=644
  sudo: true
