---
#Music
- name: stat Music dir
  stat: path=~/Music
  register: st
- debug: msg="Music folder is Exists; {{ st.stat.exists }} | isDir; {{ st.stat.isdir }}"
- name: Delete the original Music folder
  file: state=absent path="~/Music"
  when: st.stat.exists and st.stat.isdir
- name: Music symlink
  file: state=link path="~/Music" src="/media/mark/data/Music"

#Pictures
- name: stat Pictures dir
  stat: path=~/Pictures
  register: st
- debug: msg="Pictures folder is Exists; {{ st.stat.exists }} | isDir; {{ st.stat.isdir }}"
- name: Delete the original Pictures folder
  file: state=absent path="~/Pictures"
  when: st.stat.exists and st.stat.isdir
- name: Pictures symlink
  file: state=link path="~/Pictures" src="/media/mark/data/Pictures"

#Videos
- name: stat Videos dir
  stat: path=~/Videos
  register: st
- debug: msg="Videos folder is Exists; {{ st.stat.exists }} | isDir; {{ st.stat.isdir }}"
- name: Delete the original Videos folder
  file: state=absent path="~/Videos"
  when: st.stat.exists and st.stat.isdir
- name: Videos symlink
  file: state=link path="~/Videos" src="/media/mark/data/Videos"
