---
- name: ensure compizconfig is installed
  apt: pkg=python-compizconfig
- name: install ccsm
  apt: pkg=compizconfig-settings-manager
- name: make work directory
  file: path=/tmp/compiz_import state=directory
- name: copy import script
  copy: src=import_compiz.py dest=/tmp/compiz_import/import_compiz.py mode=0775
- name: copy profile 
  copy: src=default.profile dest=/tmp/compiz_import/default.profile
- name: run compiz import
  command: /tmp/compiz_import/import_compiz.py /tmp/compiz_import/default.profile
- name: cleanup
  file: path=/tmp/compiz_import state=absent
